###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "admin@admin.com",
    "password": "123456789admin"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "admin@admin.com",
    "password": "123456789admin"
}


